# Server Properties
server:
  port: 8080
  servlet:
    context-path: /pizza-manager

#logging
logging:
  info:
    path: ./target/log
    name: info
  error:
    path: ./target/log
    name: error

# Swagger activation
springdoc:
  api-docs:
    enabled: true
    path: /swagger-ui/v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

#MongoDB connection
spring:
  data:
    mongodb:
      uri: mongodb://pizza-user:pizza-password@localhost:27017/pizza-awesome-db?authSource=admin

awesomePizzaManager:
  intervalMinutes: 15